rules:
  - id: xss
    patterns:
      - pattern: document.write(...)
      - pattern: $ELEMENT.innerHTML = ...
      - pattern: element.insertAdjacentHTML(...)
    message: "Erreur de sécurité: XSS possible"
    languages: [javascript]
    severity: ERROR