name: Vercel Production Deployment

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      production_url: ${{ steps.deploy.outputs.production_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy Project to Vercel
        id: deploy
        run: |
          set -e
          echo "Starting deployment..."
          DEPLOYMENT_OUTPUT=$(vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes --confirm)
          echo "Deployment output: $DEPLOYMENT_OUTPUT"
          PRODUCTION_URL=$(echo "$DEPLOYMENT_OUTPUT" | grep -o 'https://[^ ]*' | head -n 1)
          echo "Extracted Production URL: $PRODUCTION_URL"
          if [ -z "$PRODUCTION_URL" ]; then
            echo "No production URL found in deployment output"
            exit 1
          fi
          echo "::set-output name=production_url::$PRODUCTION_URL"
      
      - name: Log Production URL
        run: echo "Production URL is ${{ steps.deploy.outputs.production_url }}"

  comment:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Comment on Commit
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_GITHUB }}
          script: |
            const productionUrl = "${{ needs.deploy.outputs.production_url }}";
            const commit = context.sha;
            if (commit) {
              const message = productionUrl ? `🚀 Production deployment is ready! Here is the URL: ${productionUrl}` : '⚠️ Production deployment failed.';
              await github.rest.repos.createCommitComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: commit,
                body: message
              });
            }
