name: Deploy and Comment on PR

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches-ignore:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        
      - name: Install dependencies
        run: npm install

      - name: Deploy to Vercel
        id: deploy
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          VERCEL_DEPLOY_URL=$(vercel --prod --token ${{ secrets.VERCEL_TOKEN }} | grep "Preview URL" | cut -d' ' -f3)
          echo "::set-output name=preview_url::$VERCEL_DEPLOY_URL"

      - name: Comment PR with preview URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const previewUrl = ${{ steps.deploy.outputs.preview_url }};
            github.rest.issues.createComment({
              issue_number: github.event.pull_request.number,
              owner: github.repository_owner,
              repo: github.repository,
              body: `Deployed preview is ready! [View Preview](${previewUrl})`
            })
