name: Vercel Deployment and Comment

on:
  push:
    branches-ignore:
      - main
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: npm install
      
      - name: Deploy to Vercel
        id: vercel-deploy
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Output deployment URL
        run: echo "The deployment URL is ${{ steps.vercel-deploy.outputs.preview-url }}"

      - name: Comment on Pull Request
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const deploymentUrl = "${{ steps.vercel-deploy.outputs.preview-url }}";
            github.rest.issues.createComment({
              issue_number: github.event.pull_request.number,
              owner: github.repository_owner,
              repo: github.repository,
              body: `🚀 Deploy preview ready! [View Preview](${deploymentUrl})`
            })
