name: Vercel Deployment and Comment

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Vercel Deploy
        id: vercel-deploy
        run: |
          DEPLOYMENT_OUTPUT=$(vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --scope your-vercel-scope)
          echo "Deployment output: $DEPLOYMENT_OUTPUT"
          PREVIEW_URL=$(echo "$DEPLOYMENT_OUTPUT" | grep -o "https://[^ ]*vercel.app")
          echo "::set-output name=preview_url::$PREVIEW_URL"
      
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v4
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: github.event.pull_request.number,
              owner: github.repository_owner,
              repo: github.repository,
              body: `🚀 Preview URL: ${{ steps.vercel-deploy.outputs.preview_url }}`
            })
