name: Vercel Preview Deployment

on:
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy Project to Vercel
        run: vercel --token=${{ secrets.VERCEL_TOKEN }} --confirm
      - name: Get Preview URL
        run: | 
          echo "Preview URL: $(vercel --token=${{ secrets.VERCEL_TOKEN }} list | grep 'Ready' | head -1 | awk '{print $2}')"