name: Vercel Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      production_url: ${{ steps.get_url.outputs.url }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Deploy Project to Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm
      - name: Get Production URL
        id: get_url
        run: echo "::set-output name=url::$(vercel --token=${{ secrets.VERCEL_TOKEN }} list | grep 'Ready' | head -1 | awk '{print $2}')"

  comment:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Comment on commit
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const sha = github.context.sha;
            const url = `${{ needs.deploy.outputs.production_url }}`;
            const message = `Production deployment is ready! [Production URL](${url})`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: sha,
              body: '👋 Thanks for using git script!'

            });
